name: Periodic

on:
  workflow-dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  periodic:
    name: Periodic
    runs-on: ubuntu-latest

    steps:
      - name: Periodic
        steps: echo 'Mensaje automatico'
